version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 vercel_app.wsgi:application
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key
      - DJANGO_DEBUG=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5