# Generated by Django 4.1.3 on 2024-03-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="delivery_status",
            field=models.CharField(default="Pending", max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="canteen.orders",
            ),
        ),
    ]
