# Generated by Django 4.1.3 on 2024-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0002_alter_orders_delivery_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
