# Generated by Django 4.1.3 on 2024-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_orderdetails_isdelivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='rating',
            field=models.IntegerField(blank=True, default=0, max_length=1, null=True),
        ),
    ]
